### PR TITLE
Add comment support to records

### PR DESCRIPTION
**Pull request by glensc**
Simple string value. <del>As record is typed as any, no documentation changes.</del>

### CODE REVIEW

**Comment by RoseSecurity** [comment]
@glensc Thanks for the contribution! Is there any way you would also be able to add a description entry for comments in the [record variable](https://github.com/cloudposse/terraform-cloudflare-zone/blob/41e086c19a7b14f47a19a6713998321ebb4a8ac0/variables.tf#L17)?

**Comment by glensc** [comment]
41e086c19a7b14f47a19a6713998321ebb4a8ac0

**Comment by RoseSecurity** [comment]
I believe the tests are failing due to a previous subscription update, but this looks good to me

**Review by RoseSecurity — APPROVED** [review]
Thanks for the contribution!

**Comment by glensc** [comment]
Any take on https://github.com/cloudposse/terraform-cloudflare-zone/pull/48?

**Pull request merged**
